openapi: 3.2.0

info:
  title: "sample_back Document"
  version: "0.0.1"
  description: "sample_backのドキュメント"

servers:
  - url: http://localhost:8080
    description: Local development server

paths:
  # loginパス
  /login:
    post:
      operationId: loginUser
      description: ユーザーログイン
      summary: ユーザーログイン
      security: [] # 認証方式未定のため一旦認証不要
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/requestLogin"
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/successLoginUser"
          description: "Successfully"
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errorResponse"
          description: "Client Error"
        "500":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errorResponse"
          description: "Internal Server Error"

  # ユーザー登録
  /registUser:
    post:
      operationId: registUser
      description: ユーザー登録
      summary: ユーザー登録
      security: [] # 認証方式未定のため一旦認証不要
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/requestRegistUser"
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/successRegistUser"
          description: "Successfully"
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errorResponse"
          description: "Client Error"
        "401":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errorResponse"
          description: "Unauthorized"
        "500":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errorResponse"
          description: "Internal Server Error"

components:
  schemas:
    #レスポンスステータスコード（200）
    successResponseInfo:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
          example: "200"
        message:
          type: string
          example: successfully
    #レスポンスステータスコード（エラー）
    errorResponseInfo:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
          example: "500"
        message:
          type: string
          example: error
    #ユーザー登録成功のレスポンスフォーマット
    successRegistUser:
      allOf:
        - type: [object, "null"]
          properties:
            responseInfo:
              $ref: "#/components/schemas/successResponseInfo"
            data:
              $ref: "#/components/schemas/responseSuccessRegistUser"
    #APIレスポンスフォーマット（エラー）
    #すべてのエンドポイントの共通レスポンスフォーマット
    errorResponse:
      allOf:
        - type: object
          properties:
            responseInfo:
              $ref: "#/components/schemas/errorResponseInfo"
            data:
              $ref: "#/components/schemas/errorData"

    #ログイン成功のレスポンスフォーマット
    successLoginUser:
      allOf:
        - type: [object, "null"]
          properties:
            responseInfo:
              $ref: "#/components/schemas/successResponseInfo"
            data:
              $ref: "#/components/schemas/successLogin"

    #ログイン時のリクエスト
    requestLogin:
      required:
        - userId
        - password
      type: object
      properties:
        userId:
          type: string
          minLength: 1
          maxLength: 32
          example: sampleUserId1
        password:
          type: string
          format: password
          minLength: 8
          maxLength: 64
          example: samplePassword1
    # ログイン成功時のレスポンスデータ
    successLogin:
      required:
        - userId
      type: object
      properties:
        userId:
          type: string
          example: sampleUserId1
        userName:
          type: string
          example: sample UserName1
        loginCheck:
          type: boolean
          example: true
        message:
          type: string
          example: "ログインに成功しました。"

    #ユーザー登録時のリクエスト
    requestRegistUser:
      required:
        - userId
        - userName
        - password
      type: object
      properties:
        userId:
          type: string
          minLength: 1
          maxLength: 32
          example: sampleUserId1
        userName:
          type: string
          minLength: 1
          maxLength: 64
          example: sampleUserName1
        password:
          type: string
          format: password
          minLength: 1
          maxLength: 64
          example: samplePassword1
    #ユーザー登録成功
    responseSuccessRegistUser:
      required:
        - userId
        - userName
        - loginCheck
        - message
      type: object
      properties:
        userId:
          type: string
          minLength: 1
          maxLength: 32
          example: sampleUserId1
        userName:
          type: string
          minLength: 1
          maxLength: 64
          example: sampleUserName1
        loginCheck:
          type: boolean
          example: true
        message:
          type: string
          example: ユーザー登録に成功しました。
    #ユーザー登録失敗
    errorData:
      type: object
      properties:
        userId:
          type: string
          minLength: 1
          maxLength: 32
          example: "sampleUserId1"
        userName:
          type: string
          minLength: 1
          maxLength: 64
          example: "sampleUserName1"
        loginCheck:
          type: boolean
          example: false
        message:
          type: string
          example: サンプルエラー。
